### ISSUE TITLE
Xiaomi/aqara vibration sensor

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#10]
Hi,

I hope you can add support for the aqara vibration sensor.

The ID is lumi.vibration.aq1

Website: https://www.aliexpress.com/item/32892903643.html

Here is some more information from developer.athom.com:

"type":string"EndDevice"
"ieeeAddr":string"0x00158d0002a92083"
"nwkAddr":int61572
"manufId":int4151
"epList":[...]2 items
"status":string"offline"
"joinTime":NULL
"name":string"Aqara Vibration Sensor"
"profileId":string"260"
"deviceId":string"10"
"manufacturerName":string"LUMI"
"productId":string"lumi.vibration.aq1"

**Comment by powermarcel10** [comment]
And here allready some more information about the vibration settings.

Just some code, not specified yet..

2019-12-05 14:33:15 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '80',
  r: 'sensors',
  state:
   { lastupdated: '2019-12-05T13:33:15',
     orientation: [ 6, -4, 83 ],
     tiltangle: 360,
     vibration: true },
  t: 'event',
  uniqueid: '00:15:8d:00:02:a9:20:83-01-0101' }
2019-12-05 14:33:17 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '80',
  r: 'sensors',
  state:
   { lastupdated: '2019-12-05T13:33:17',
     orientation: [ 1, 0, 89 ],
     tiltangle: 360,
     vibration: true },
  t: 'event',
  uniqueid: '00:15:8d:00:02:a9:20:83-01-0101' }
2019-12-05 14:33:04 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '80',
  r: 'sensors',
  state: { lastupdated: '2019-12-05T13:33:04', vibration: true },
  t: 'event',
  uniqueid: '00:15:8d:00:02:a9:20:83-01-0101' }
2019-12-05 14:32:52 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '80',
  name: 'Vibration Sensor',
  r: 'sensors',
  t: 'event',
  uniqueid: '00:15:8d:00:02:a9:20:83-01-0101' }
2019-12-05 14:32:51 [log] [deCONZ] Update for unregistered device { e: 'added',
  id: '80',
  r: 'sensors',
  sensor:
   { config:
      { battery: null,
        on: true,
        pending: [],
        reachable: true,
        sensitivity: null,
        sensitivitymax: 21,
        temperature: null },
     ep: 1,
     etag: '6e3a3b3c7a8c020a4b942c4506c11179',
     id: '80',
     manufacturername: 'LUMI',
     modelid: 'lumi.vibration.aq1',
     name: 'Vibration 80',
     state:
      { lastupdated: 'none',
        orientation: [Array],
        tiltangle: null,
        vibration: false,
        vibrationstrength: null },
     type: 'ZHAVibration',
     uniqueid: '00:15:8d:00:02:a9:20:83-01-0101' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:a9:20:83-01-0101' }

If you need more information, please let me know.

Regards,
Marcel

**Comment by notabene00** [comment]
I see the binary `vibration`, integer `tiltangle` and array of integers `orientation`
What triggers/conditions.. capabilities overall are expected for this device?

**Comment by powermarcel10** [comment]
Please see this post: https://community.athom.com/t/xiaomi-aqara-smart-home-zigbee-app-v0-6-2/156/82?u

**Comment by notabene00** [comment]
Oh. I doubt if I'll be able to implement all of this without device on hand

**Comment by powermarcel10** [comment]
I do understand. If there is anything specific I can do please let me know.

**Comment by joeblack2k** [comment]
Can i paypal you a few bucks so you can get one ?

**Comment by notabene00** [comment]
@joeblack2k yes, if you would like to

**Comment by joeblack2k** [comment]
Sure! DM me your paypal :)

Maybe include donations in the readme i think allot of people will support a “coffee” for the author :)

**Comment by notabene00** [comment]
<img width="659" alt="Снимок экрана 2019-12-11 в 02 03 39" src="https://user-images.githubusercontent.com/9576189/70576626-750ee980-1bba-11ea-9290-c1f287c6dccd.png">

@joeblack2k that `Sponsor` button on the top doing something similar ;)
but you're right, maybe I'll place it somewhere in sight
because if you're missed the button, the others might too

**Comment by joeblack2k** [comment]
Hmm i didn't see that no.. 

i send you $20 should be enough to buy some Xaomi toys :)

**Comment by notabene00** [comment]
> send you $ 20

Got 'em
I'll order the sensor soon

**Comment by notabene00** [comment]
<img width="354" alt="Снимок экрана 2020-01-13 в 12 29 12" src="https://user-images.githubusercontent.com/9576189/72244903-5019f600-3600-11ea-8d30-9a9da5cf3480.png">
@joeblack2k sensor's here

Will work on its support soon

**Comment by notabene00** [comment]
https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-vibration-support
no triggers yet (almost useless for now) but you can see the data already
<img width="375" alt="image" src="https://user-images.githubusercontent.com/9576189/72251141-4a2b1180-360e-11ea-9e71-049e1e294708.png">

**Comment by fantomnotabene** [comment]
https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-vibration-support
Could someone test?
![IMG_2587](https://user-images.githubusercontent.com/9576189/72255969-1ef9ef80-3619-11ea-80f8-f94e62d3704b.PNG)
![IMG_2590](https://user-images.githubusercontent.com/9576189/72255974-1f928600-3619-11ea-8769-1ca2e6afe823.PNG)

**Comment by notabene00** [comment]
Triggers in da house :)
Vibration `strength` is available under `vibration alarm on` as token
The same with `angle` and `relative angle` under `tilt alarm on`

**Comment by joeblack2k** [comment]
Thank you!!! Awesome dude as always

**Comment by notabene00** [comment]
@joeblack2k can you confirm I should merge the branch?

**Comment by joeblack2k** [comment]
Confirmed! Works (sorry late reaction my son was born )

**Comment by notabene00** [comment]
welcome to the world, little one :)
