### ISSUE TITLE
Trådfri motion sensor

### ISSUE THREAD

**Issue by notabene00** [fantomnotabene/HomeyCONZ#14]
**Device name:**

Trådfri motion sensor

**Device link:**

https://www.ikea.com/gb/en/p/tradfri-wireless-motion-sensor-white-70429913/

**Device modelid:**

`TRADFRI motion sensor`

**Device capabilities:**

Motion, binary luminance sensor

**State report example:**

```javascript
state:
      { dark: true,
        lastupdated: '2019-07-14T21:08:45',
        presence: false }
```

**Comment by notabene00** [comment]
@k4mrat can you test?
https://github.com/fantomnotabene/HomeyCONZ/tree/tradfri-motion-sensor

**Comment by k4mrat** [comment]
I’ll try it ASAP, hopefully after work tonight!

**Comment by k4mrat** [comment]
Nice going!
It pairs fine. 
The dark/light works! (See issues below)

Issues:
• Don’t know if you made a flow card for “if dark” but I can’t find one.

•I haven’t had time to test very thoroughly before I go to sleep tonight, but for 4 minutes the motion alarm never canceled, but the light/dark Boolean flipped when motion was triggered and that time was reset to 0. 

•Something I stumbled upon when I tried to map the sensor, and realized that it had this Boolean, was that when the button is set to “Night” it reacts with dark true/false correctly. But when set to “Day” it seems to send only Dark:true. I thought it was me doing something wrong, but it seems like the same thing happens now with this driver. I’m suspecting IKEA might have messed something up here. It would have been more logical to have Boolean “Light:true/false” than “Dark” IMO. (Or I’m missing something!)

**Comment by k4mrat** [comment]
![Uploading 1E1CCBDD-A9F9-460C-9643-2CAA95042299.png…]()
![Uploading 85E02C8E-5BCA-4D5B-A5CE-160913A9AA7F.png…]()

**Comment by k4mrat** [comment]
Night on: Dark correctly

![A9245A3F-8C61-4B77-B8E6-0976E8828647](https://user-images.githubusercontent.com/48549512/69997351-42c71180-1554-11ea-9055-5567e4f4b97a.png)

**Comment by k4mrat** [comment]
Night on: also correct

![4EEFEE06-92D7-48B3-9D28-65CB3874A50F](https://user-images.githubusercontent.com/48549512/69997370-52465a80-1554-11ea-81d1-fa37c2d78a8b.png)

**Comment by k4mrat** [comment]
Day mode on: Reports Dark:true. Not your fault though I’d say!

But motion is never canceled. Will look more at that tomorrow. 

![A42C4453-1CB1-47CB-B212-367207554008](https://user-images.githubusercontent.com/48549512/69997413-67bb8480-1554-11ea-9673-80bb49013b37.png)

**Comment by notabene00** [comment]
> Don’t know if you made a flow card for “if dark” but I can’t find one

No, work in progress. It pairs - already a good feedback :)

> Not your fault

So it is not working as expected, but not my bad?

> motion is never canceled

Can you leave the room and wait a couple minutes? 
Maybe 3-4

**Comment by notabene00** [comment]
@k4mrat [branch](https://github.com/fantomnotabene/HomeyCONZ/tree/tradfri-motion-sensor) updated
added condition flow card
check if it works too

**Comment by k4mrat** [comment]
> So it is not working as expected, but not my bad?

Not if I’m right about this:

> •Something I stumbled upon when I tried to map the sensor, and realized that it had this Boolean, was that when the button is set to “Night” it reacts with dark true/false correctly. But when set to “Day” it seems to send only Dark:true. I thought it was me doing something wrong, but it seems like the same thing happens now with this driver. I’m suspecting IKEA might have messed something up here. It would have been more logical to have Boolean “Light:true/false” than “Dark” IMO. (Or I’m missing something!)

_______

> Can you leave the room and wait a couple minutes?
> Maybe 3-4

I’ll give that a try!

**Comment by k4mrat** [comment]
The motion sensor resets itself perfectly now it seems!

Got some more info about the Boolean and maybe why it may behaves the way it does.

The new version seems to have the ability to dim lights to like 30% or 100% depending on dark or not. The old one, when used as intended; directly with a Trådfri LED, is either ON or OFF. 

The Night/Day setting on the back of it is just to tell the lights if you want them to only turn on when dark or always. This is probably why the Day-setting always sends “Dark:True” as this tells the LEDs to turn on.

**Comment by notabene00** [comment]
@k4mrat so.. can I say that TMS is fully implemented and should be merged?

**Comment by k4mrat** [comment]
Yeah.
Might wanna make a note somewhere about the “is dark” only working if set to “Night” mode.

**Comment by notabene00** [comment]
I have no idea where
