### ISSUE TITLE
Hue color light not able to change color

### ISSUE THREAD

**Issue by Vissertje1980** [fantomnotabene/HomeyCONZ#18]
I have just installed your app on my homey to controle devices on deCONZ. It works really great en i am verry thankfull for this great app.

I heave a little problem and that's that i can not change the color of my hue color bulb's. Only from white to warm white. 

Hope you can fix this.

Best regards 
Jan Willem Visser

**Comment by notabene00** [comment]
Will look into it this weekend, I think
Thanks for reporting

**Comment by Vissertje1980** [comment]
thank you very much, enjoy your weekend

**Comment by notabene00** [comment]
https://github.com/fantomnotabene/HomeyCONZ/tree/bulb-colors
@Vissertje1980 Can you try the branch above?

**Comment by Vissertje1980** [comment]
Later today when i have some time i gonna try it. Thank you very much so far

**Comment by Vissertje1980** [comment]
i just installed the update and the color change works, great work and thank you very much
