### ISSUE TITLE
Xiaomi motion sensor reset after 5 seconds

### ISSUE THREAD

**Issue by Vissertje1980** [fantomnotabene/HomeyCONZ#19]
Hello,

I have modified all my xiaomi motion (with and without light metering) sensors to get a motion alarm of 5 seconds. Is it possible to implement the possibility to turning the motion alarm off after 5 seconds? 

Best regards Jan Willem

**Comment by notabene00** [comment]
Hi

Yes, it is possible, but it has no deal with this app

You can:
```bash
curl -H 'Content-Type: application/json' -X PUT -d '{"duration": 5}' http://phoscon_ip_here:80/api/api_key_here/sensors/motion_sensor_id_here/config
```
for each of your sensors

Then they will "report" `no motion` in 5 seconds and my app will react accordingly - start `no motion timer` after 5 seconds
Actually they're not reporting it, the other side (deCONZ itself) just saying "no motion for X seconds", so turn `motion` off
That `X` we set in the put request above

**Comment by Vissertje1980** [comment]
Thank you very much for you replay. Gonna look at it :-)
