### ISSUE TITLE
Philips Motion Sensor

### ISSUE THREAD

**Issue by joeblack2k** [fantomnotabene/HomeyCONZ#22]
Hey,

I thought the Philips Motion Sensor was supported? I suddenly disappeared..  😅

**Comment by notabene00** [comment]
hello
what are you talking about?
latest master, v0.12.0, updated a week ago
just checked (can't really check if it works because I have no these sensors)
![IMG_3B9AA4502BBF-1](https://user-images.githubusercontent.com/9576189/71254931-8768f000-233d-11ea-9a4d-83177d2a8325.jpeg)

**Comment by joeblack2k** [comment]
i'm really stupid.. i updated the wrong (older) folder haha stupid me
