### ISSUE TITLE
Philips Iris light doesn't have color

### ISSUE THREAD

**Issue by joeblack2k** [fantomnotabene/HomeyCONZ#24]
While the other error is fixed by using app runn, the philips iris light still doesnt have color options in homey

this is the information i have:
"18":{"etag":"457ef0f9fbed5cb1d9b335aa3b79f080","hascolor":true,"manufacturername":"Philips","modelid":"LLC010","name":"Philips Hue Iris","state":{"alert":"none","bri":109,"colormode":"xy","effect":"none","hue":9046,"on":true,"reachable":true,"sat":173,"xy":[0.5412,0.4007]},"swversion":"420067D5","type":"Color light","uniqueid":"00:17:88:01:00:11:e2:c7-0b"},

if you need other info please let me know how to get it.

thank you in advance!

**Comment by notabene00** [comment]
No, that's all I need, I think
You should try https://github.com/fantomnotabene/HomeyCONZ/tree/bulb-colors
Re-add lights after updating to the branch above

**Comment by joeblack2k** [comment]
Works perfect!!

**Comment by notabene00** [comment]
Color picker itself too?

**Comment by joeblack2k** [comment]
Yup tested all colors :)

**Comment by notabene00** [comment]
I'll close this when branch `bulb-colors` will be merged
