### ISSUE TITLE
[Feature suggestion] Add "Request API key" button in app

### ISSUE THREAD

**Issue by cbho** [fantomnotabene/HomeyCONZ#27]
**Setup:**
Intel NUC with hass.io 0.103.5 running on a Proxmox VE (Debian Buster) with the deCONZ hass.io addon (v 5.0) - have connection between the USB-stick (ConBee v1, updated fw) and hass.io.

**Problem:**
When running "autodiscover" in HomeyCONZ it says "Succesfully discovered gateway" (yes, has activated "Authenticate app" in the Phoscon webinterface) - but it doesn't get a API-key...
It detects the internal ip-adress (172.30.33.0) in HomeyCONZ - I can change it in the HomeyCONZ-app to the ip-adress of my NUC (192.168.1.3) and set the ports as they are in the addon - but then have to manually get the API key using command prompt...

**Suggestion:**
Adding a button in the app that makes it possible to fill in the IP address and ports and then request an API key via the app (thereby eliminating the need for going via the command promt to get it...)

**Comment by notabene00** [comment]
Something like this is already implemented, but yes, some improvements needed
