### ISSUE TITLE
Colour picker not working on Ikea Trådfri bulb (E27 CWS opal 600lm LED1624G9)

### ISSUE THREAD

**Issue by cbho** [fantomnotabene/HomeyCONZ#28]
**Describe the bug:**
- Changing colour using the colour picker in Homey doesn't change the colour of the light on the bulb.
- Switching the bulb on/off and changing dim-level via Homey works perfect
- Changing colour via deCONZ/Phoscon webinterface works perfect

**How it should work:**

**Additional context:**
- HomeyCONZ version as of Dec. 30th 2019
- deCONZ/Phoscon running as addon (v. 5.0) on hass.io (0.103.5) in a Proxmox VM (Debian Buster) on Intel Nuc with a ConBee (fw 2.05.72)

**Comment by giggo** [comment]
I see the same. 
If I change color saturation in Phoscon web app and color in Homey afterwards it works fine. It seems that color saturation needs to be set/defaulted somehow first but Homey has no saturation picker. Color picker shows up in Homey.
