### ISSUE TITLE
Feature request - Group support

### ISSUE THREAD

**Issue by jtebbens** [fantomnotabene/HomeyCONZ#29]
Please add group support for devices.
This way it would be easier to turn a collection of bulbs (all kitchen etc) on.

https://dresden-elektronik.github.io/deconz-rest-doc/groups/#setstate

**Comment by notabene00** [comment]
Yes, good thought, I will look into it

**Comment by notabene00** [comment]
Can you test?
https://github.com/fantomnotabene/HomeyCONZ/tree/groups-support

**Comment by jtebbens** [comment]
Tested and confirmed working.

Thanks!

**Comment by jtebbens** [comment]
Only thing I notice is the group status doesn't change if you turn of a light in the group that the group will turn off as well.

**Comment by jtebbens** [comment]
Only thing I notice is the group status doesn't change if you turn of a 
light in the group that the group will turn off as well.

**Comment by notabene00** [comment]
@jtebbens try now
https://github.com/fantomnotabene/HomeyCONZ/tree/groups-support

**Comment by jtebbens** [comment]
Thank you will test

Verstuurd vanaf mijn iPhone

Op 13 jan. 2020 om 10:58 heeft Елизаров Роман Русланович <notifications@github.com> het volgende geschreven:

﻿

@jtebbens try now
https://github.com/fantomnotabene/HomeyCONZ/tree/groups-support

**Comment by jtebbens** [comment]
@fantomnotabene confirmed working!
