### ISSUE TITLE
side support for aqara cube

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#30]
Hi! 

I have a request.. Adding support for wich side the aqara cube is on.. I think you've told me that is is a lot of work to add this.. But is it not only adding 6 extra commands? It will be really usefull as it will extend the possibilitys of this device endless.

For now I'm using the cube to the xiaomi/aqara app on homey as this is supported there but offcourse I do prefer using all my devices running your app. I hope you will reconsider this..

Thanks!

**Comment by notabene00** [comment]
try https://github.com/fantomnotabene/HomeyCONZ/tree/cube-sides-conditions-support

**Comment by powermarcel10** [comment]
Thanks! I will try it asap. One thing, is this screen also working or something similar too see what the state of the cube is:

![Screenshot_2020-01-16-11-46-27-884_app homey](https://user-images.githubusercontent.com/2340835/72518615-06c2e400-3856-11ea-8f1a-3581c94f114f.jpg)

**Comment by notabene00** [comment]
> what the state of the cube is

Implemented side up capability. If you wanna see others, open separate issue.

**Comment by powermarcel10** [comment]
Allright thanks. Tested the sides and it is working great! Thanks a lot!
