### ISSUE TITLE
groups do not update their status after reboot deconz. 

### ISSUE THREAD

**Issue by snippem** [fantomnotabene/HomeyCONZ#39]
After a reboot of the homeyconz app in homey or rebooting deconz the homeyconz app gives a red triangle at all of the groups.
All of the separate lights and plugs etc keeps working fine without the red triangle.
The groups are updated in their status on or off but with a red triangle and you can't controll the groups anymore.
To get it working again you have to reboot homey and all of the groups are working again.

**Comment by tpnprins** [comment]
Also encountered this issue, even with version 0.13.4. All devices work, except for the light groups which show a red triangle. Upon trying to control them the error ‘websocket is down’ appears. Rebooting deconz or homeyconz does not help, rebooting Homey does.

**Comment by djeskoswe** [comment]
Same here how can we help ?
