### ISSUE TITLE
HomeyCONZ crashes when activating scene created in Phoscon

### ISSUE THREAD

**Issue by mickeman** [fantomnotabene/HomeyCONZ#42]
When i activate a scene that is created in phoscon the HomeyCONZ app crashes. 
Deconz ver 2.05.72
Homey ver 3.2.1
HomeyCONZ ver 0.13.4
This problem is not new for me but i havent figured out why it crashed until today.
Could someone confirm this or is it just me having this problem?

![Screenshot_20200214-110854](https://user-images.githubusercontent.com/37731791/74522108-e5b7e680-4f1a-11ea-9603-7905561295fe.jpg)

**Comment by notabene00** [comment]
I'll look into this soon

**Comment by mickeman** [comment]
Thank you very much for fixing this! 👍

**Comment by notabene00** [comment]
Better late than never :)
