### ISSUE TITLE
Homey rolled out Homey+ backups, but not for CLI apps

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#43]
Hi! In the first place; congratulations with the birth of your kid! Must have been a really rollercoster for you the last couple of months! I hope everything is fine with you and your family.

I have a question.. Homey has rolled out the Homey+ service, wich contains for now Homey backups. This is awesome as all devices and flows are stored in the cloud for when something happend to homey. Everything can be stored back...

Almost... Because only official apps and devices are backed up. Apps that are installed by CLI, like Homeyconz are not backuped. In my case, almost all my devices are connected to Deconz, so the backup function is almost useless for me..

So my request; I hope you want to publish this app officially in the homey appstore.. What are your thoughts about this?

Cheers,
Marcel

**Comment by notabene00** [comment]
Hi
I have a small amount of time now, but once I will
This issue will track it till complete

**Comment by gajdur** [comment]
Hi @powermarcel10 i can confirm that homeyconz settings are backuped and restored on my new homey pro, all you need to do is to install the app again from cli.

**Comment by powermarcel10** [comment]
> Hi @powermarcel10 i can confirm that homeyconz settings are backuped and restored on my new homey pro, all you need to do is to install the app again from cli.

Thanks for testing! That's nice.. But what about the devices and flows? Everything is present again..?

**Comment by gajdur** [comment]
Yep, everything was ok.

**Comment by notabene00** [comment]
I think, this one might be closed 
Because:
- backups are working for CLI apps
- we now have #45 for tracking app on its way to the app store
