### ISSUE TITLE
Why not put the app in the store?

### ISSUE THREAD

**Issue by MadMonkey87** [fantomnotabene/HomeyCONZ#45]
**Describe the bug:**
This is a great plus for homey, but I cannot find it in the official store. Is there a particular reason it isn't there?

**How to reproduce:**
 go apps, click on add, search for "homeyConz" or "deconz" or just "conz" -> no app could be found.

**Comment by notabene00** [comment]
No, there is no particular reason not to be there
But I can't just put it in store, doing so requires some preparations
Lately I've not enough time for developing this app or even fixing bugs
I'll be glad if someone help me

**Comment by MadMonkey87** [comment]
I've created a heavily modified fork and put it into the store:)
