### ISSUE TITLE
INNR SP120

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#5]
**Device name:**
INNR SP120

**Device link:**
http://www.innrlighting.com/nl/service/#faq-290

**Device modelid:**
SP 120

**Device capabilities:**
On/off/power/energy

**State report example:**
"type":

string"Router"

"ieeeAddr":

string"0x00158d0003273daa"

"nwkAddr":

int63239

"manufId":

int4454

"manufName":

string"innr"

"powerSource":

string"Mains (single phase)"

"modelId":

string"SP 120"

"epList":[

...

]

2 items

"status":

string"online"

"joinTime":

int1574989941

"name":

string"Telefoon lader"

"profileId":

string"49246"

"deviceId":

string"16"

"manufacturerName":

string"innr"

"productId":

string"SP 120"

**Comment by notabene00** [comment]
Check if it already works via plug driver.

**Comment by powermarcel10** [comment]
I checked it and it is working! Including power measurement. Awesome! So this one can be closed..

**Comment by notabene00** [comment]
So any smart plug should work, thanks for testing ;)
