### ISSUE TITLE
Support for IKEA TRÅDFRI remote control

### ISSUE THREAD

**Issue by joeblack2k** [fantomnotabene/HomeyCONZ#6]
Is it possible to add support for the TRÅDFRI remote control ?

         },
         "ep":1,
         "etag":"15fbe698572d6a2e13aaa6d023200b10",
         "manufacturername":"IKEA of Sweden",
         "mode":3,
         "modelid":"TRADFRI remote control",
         "name":"TRÅDFRI remote control",
         "state":{
            "buttonevent":1002,
            "lastupdated":"2019-11-23T12:40:19"
         },
         "swversion":"1.2.214",
         "type":"ZHASwitch",
         "uniqueid":"00:0d:6f:ff:fe:18:e5:a7-01-1000"
      },
      "11":{
         "config":{
            "battery":100,
            "duration":90,
            "on":true,
            "reachable":true,
            "temperature":null
         },

**Comment by notabene00** [comment]
Yes, I'm waiting for PR
I think it takes a couple of days or so to be on master

**Comment by joeblack2k** [comment]
Hero! thank you!
