### ISSUE TITLE
Philips hue motion sensor

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#7]
Hi!

I hope you can add support for the Philips hue motion sensors.

I have connected 5 of them now directly to the hue bridge, but like to add them to deconz because of the delay when I connect them to the bridge and than to homey.

I have no further information about the sensors. Do you need any other info?

Here is a link: https://www2.meethue.com/en-us/p/hue-motion-sensor/046677473389

There is also an outdoor version wich I consider to buy: https://www2.meethue.com/nl-nl/p/hue-buitensensor/8718699625474

Regards,
Marcel

**Comment by notabene00** [comment]
Yes, philips hue motion sensors should work with the #3 
But they has a binary luminance sensor, which is not supported for now
I'll add this sensor as soon as their full support will be ready

**Comment by notabene00** [comment]
You can just `athom app run` HomeyCONZ and look for the output.
There will be something like 
```javascript
Update for unregistered device { e: 'changed',
  id: '23',
  r: 'sensors',
  state: 
   { dark: false,
     daylight: true,
     lastupdated: '2019-12-02T11:17:09',
     lightlevel: 19191,
     lux: 83 },
  t: 'event',
  uniqueid: '00:15:8d:00:02:e2:e9:20-01-0400' }
```
where `id: '23'` is id for your Hue motion sensor.
This data would be really helpful.

Notice: one physical sensor can use two or more ids. One for motion, one for luminance, one e.g. for temperature, etc.

**Comment by powermarcel10** [comment]
So I have to add them to deconz, and than run "Athom app run" in a command prompt to see this information?

**Comment by notabene00** [comment]
Exactly.

**Comment by powermarcel10** [comment]
Allright thanks. Let me try that tonight.

**Comment by powermarcel10** [comment]
Hi, maybe a stupid suggestion but is this not the information you need?

https://github.com/sebbebebbe/com.philips.hue.zigbee/blob/3868bd5ef03b7536477b84d6455e9a9807f1af3b/drivers/SML001/device.js

There is the code they use for the Hue zigbee app for Homey..

**Comment by notabene00** [comment]
No, deCONZ software is hiding all the communication with devices under the hood and just posting messages to websocket
So I need a modelid (to differentiate devices of this type) and examples of reporting data

**Comment by powermarcel10** [comment]
2019-12-02 20:50:39 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '61',
  r: 'sensors',
  state: { lastupdated: '2019-12-02T19:50:39', presence: false },
  t: 'event',
  uniqueid: '00:17:88:01:04:b7:ab:4d-02-0406' }

2019-12-02 20:50:40 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '4',
  r: 'sensors',
  state: { consumption: 0, lastupdated: '2019-12-02T19:50:40' },
  t: 'event',
  uniqueid: '00:15:8d:00:02:fe:0a:62-01-0702' }

2019-12-02 20:49:22 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '2',
  r: 'sensors',
  state: { consumption: 60, lastupdated: '2019-12-02T19:49:22' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:28:33:f6-01-0702' }

2019-12-02 20:49:23 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '8',
  r: 'sensors',
  state: { consumption: 1100, lastupdated: '2019-12-02T19:49:23' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:1e:e4:ab-01-0702' }

2019-12-02 20:49:26 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '10',
  r: 'sensors',
  state: { consumption: 50, lastupdated: '2019-12-02T19:49:26' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:27:3d:aa-01-0702' }

2019-12-02 20:49:29 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '6',
  r: 'sensors',
  state: { consumption: 0, lastupdated: '2019-12-02T19:49:28' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:27:0d:65-01-0702' }

2019-12-02 20:49:44 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '12',
  r: 'sensors',
  state: { consumption: 100, lastupdated: '2019-12-02T19:49:44' },
  t: 'event',
  uniqueid: '00:15:8d:00:03:56:a3:8c-01-0702' }

These are the unrigistered items I can find in the log. I asume that only the first one is from the motion sensor. The rest is power consumption so I think they are from power plugs. Normally, when the innr plugs are connected to homey directly you can see the actual power usage and the used power. I dont mind that only the first one is working now as I am only using the actual power, but maybe its the reason that they are listed as unregistered.

Strange thing that it detects only motion. No lux and temperature. They also dont in the deconz webinterface. I add them as "other" sensor, as they dont connect when I choose Philips. Really strange.

I will try to re-add them. But for now I hope Im helping a bit with the information above.

Cheers

**Comment by powermarcel10** [comment]
Allright, I have found them. I needen to tweak some settings in the deconz software to read the right values.

This is for the lux reading:

2019-12-02 21:23:41 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '66',
  r: 'sensors',
  state:
   { dark: true,
     daylight: false,
     lastupdated: '2019-12-02T20:23:41',
     lightlevel: 8057,
     lux: 6 },
  t: 'event',
  uniqueid: '00:17:88:01:04:b7:ab:4d-02-0400' }

This one for temperature:

2019-12-02 21:23:24 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '65',
  r: 'sensors',
  state: { lastupdated: '2019-12-02T20:23:24', temperature: 1783 },
  t: 'event',
  uniqueid: '00:17:88:01:04:b7:ab:4d-02-0402' }

and this one for motion:

2019-12-02 21:23:26 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '64',
  r: 'sensors',
  state: { lastupdated: '2019-12-02T20:23:26', presence: false },
  t: 'event',
  uniqueid: '00:17:88:01:04:b7:ab:4d-02-0406' }

**Comment by notabene00** [comment]
https://github.com/fantomnotabene/HomeyCONZ/tree/hue-motion-sensor
@powermarcel10 can you try?

**Comment by powermarcel10** [comment]
Yeah! You did it! Working fine.. Great job!
