### ISSUE TITLE
Philips hue remote dimmer switch

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#8]
Hi,

I hope you can add support for tephilips hue dimmer switch: 

https://www2.meethue.com/nl-nl/p/hue-dimmer-switch/8718696743157

If you need any other information, please let me know.

Best regards,
Marcel

**Comment by powermarcel10** [comment]
And also somemore information to add support for the Philips hue dimmer switch:

Uppest button pressed:

2019-12-05 14:20:04 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 1000, lastupdated: '2019-12-05T13:20:04' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Uppest button released:

2019-12-05 14:20:04 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 1002, lastupdated: '2019-12-05T13:20:04' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

First button long press:

2019-12-05 14:25:42 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 1001, lastupdated: '2019-12-05T13:25:42' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

First button long press released:

2019-12-05 14:25:43 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 1003, lastupdated: '2019-12-05T13:25:43' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

second button pressed:

2019-12-05 14:21:20 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 2000, lastupdated: '2019-12-05T13:21:19' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Second button released:

2019-12-05 14:21:20 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 2002, lastupdated: '2019-12-05T13:21:20' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Second button long press:

2019-12-05 14:27:28 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 2001, lastupdated: '2019-12-05T13:27:28' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Second button long press released:

2019-12-05 14:27:29 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 2003, lastupdated: '2019-12-05T13:27:29' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Third button pressed:

2019-12-05 14:22:30 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 3000, lastupdated: '2019-12-05T13:22:30' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Third button released:

2019-12-05 14:22:30 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 3002, lastupdated: '2019-12-05T13:22:30' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Third button long press:

2019-12-05 14:28:42 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 3001, lastupdated: '2019-12-05T13:28:42' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Third button long press released:

2019-12-05 14:28:43 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 3003, lastupdated: '2019-12-05T13:28:43' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

4th button pressed:

2019-12-05 14:23:39 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 4000, lastupdated: '2019-12-05T13:23:39' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

4th button released:

2019-12-05 14:23:39 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 4002, lastupdated: '2019-12-05T13:23:39' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

4th button long press:

2019-12-05 14:30:09 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 4001, lastupdated: '2019-12-05T13:30:09' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

4th button long press released:

2019-12-05 14:30:10 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '79',
  r: 'sensors',
  state: { buttonevent: 4003, lastupdated: '2019-12-05T13:30:10' },
  t: 'event',
  uniqueid: '00:17:88:01:10:49:3e:c0-02-fc00' }

Cheers,
Marcel

4th button long press:

**Comment by notabene00** [comment]
are `uppest` and `first` the same button?

**Comment by powermarcel10** [comment]
Yes. My bad.

**Comment by powermarcel10** [comment]
I saw that there is allready a branch with support for the Hue switch. Is it ready to test?

**Comment by notabene00** [comment]
No, Hue isn't ready, but Aqara wireless switch is
Tested and working for v2018

**Comment by powermarcel10** [comment]
> No, Hue isn't ready, but Aqara wireless switch is
> Tested and working for v2018

Allright great, should I test it allready for the 2016 model?

**Comment by notabene00** [comment]
Yes

**Comment by powermarcel10** [comment]
Is that branch based on latest master?

**Comment by notabene00** [comment]
@powermarcel10 is modelid for PH remote `RWL021`?
if yes, you can try hue remote branch

**Comment by powermarcel10** [comment]
Yes, its working!

**Comment by powermarcel10** [comment]
Only the dim up functions are missing!

![Screenshot_2019-12-12-18-17-43-971_app homey](https://user-images.githubusercontent.com/2340835/70734054-cbd80880-1d0b-11ea-85db-83c3b50ba998.jpg)

**Comment by notabene00** [comment]
fixed

**Comment by powermarcel10** [comment]
Confirmed! So this one can go to master! 👍

**Comment by notabene00** [comment]
merged
