### ISSUE TITLE
Xiaomi/aqara double button switch with batteries

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#9]
Hi,

I hope you can add support for the dubble switch on batteries from xiaomi.

The ID is lumi.sensor_86sw2Un

Here is a link to the github page of the homey app: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/config/drivers/sensor_86sw2Un.json

And here some more info from developer.athom.com:

"type":string"EndDevice"
"ieeeAddr":string"0x00158d000164042f"
"nwkAddr":int34540
"manufId":int4151
"epList":[...]3 items
"status":string"offline"
"joinTime":NULL
"name":string"Schakelaar bed"
"profileId":string"260"
"deviceId":string"24321"
"manufacturerName":string"LUMI"
"productId":string"lumi.sensor_86sw2Un"

BTW, I believe that there are 2 different versions of this switch. A 2016 and a 2018 version. I dont know the difference, but in the homey app there are 2 off them.

Best regards,
Marcel

**Comment by notabene00** [comment]
I have a couple of them, 2018s. 2018 version, afaik, sends events for double clicks, both button clicks and long clicks.

**Comment by powermarcel10** [comment]
Yes thats it. They are not yet compatible right?

**Comment by notabene00** [comment]
Not yet.

**Comment by powermarcel10** [comment]
Hi ,

here is some more info about this switch:

Left button:

2019-12-05 13:50:36 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '77',
  r: 'sensors',
  state: { buttonevent: 1002, lastupdated: '2019-12-05T12:50:36' },
  t: 'event',
  uniqueid: '00:15:8d:00:01:e1:16:a1-01-0006' }

Right button:

2019-12-05 13:50:36 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '77',
  r: 'sensors',
  state: { buttonevent: 2002, lastupdated: '2019-12-05T12:50:36' },
  t: 'event',
  uniqueid: '00:15:8d:00:01:e1:16:a1-01-0006' }

Both buttons:

2019-12-05 13:50:38 [log] [deCONZ] Update for unregistered device { e: 'changed',
  id: '77',
  r: 'sensors',
  state: { buttonevent: 3002, lastupdated: '2019-12-05T12:50:38' },
  t: 'event',
  uniqueid: '00:15:8d:00:01:e1:16:a1-01-0006' }

Cheers,
Marcel

**Comment by notabene00** [comment]
I have v2018s
What their features are not supported in v2016?

**Comment by powermarcel10** [comment]
There is no difference in features as far as I know.

**Comment by powermarcel10** [comment]
But to be sure I asked Tedtolboom, the developer of the homey app.

**Comment by powermarcel10** [comment]
I found it:

WXKG02LM	2016	lumi.sensor_86sw2Un	left/right/both: push
WXKG02LM	2018	lumi.remote.b286acn01	left/right/both: single/double-click & hold

**Comment by notabene00** [comment]
Great
Don't know if they are using the same `buttonevents` for corresponding clicks, but it seems to be so
ETA: next week

**Comment by powermarcel10** [comment]
Allright great! Im ready to test!

**Comment by notabene00** [comment]
@powermarcel10 aqara wireless switches here

> Is that branch based on latest master?

was not, now synced

**Comment by powermarcel10** [comment]
The app does not find my switches.. Tried to look for 2016 and 2018 switches..

**Comment by notabene00** [comment]
@powermarcel10 just now 
branch (have not been updated now): https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-wireless-switches
v2018: 
![IMG_B275BC7B0E8B-1](https://user-images.githubusercontent.com/9576189/70640119-87d1fe80-1c4c-11ea-8781-42da44e03c9c.jpeg)
triggers working

**Comment by notabene00** [comment]
What modelids of your switches (v2016 and v2018 accordingly)?

**Comment by powermarcel10** [comment]
Sorry I do not understand. What branch should I test now?

**Comment by powermarcel10** [comment]
I'm trying the lumi.sensor_86sw2Un wich is the 2016 version. I only have 2 of them. No 2018.

**Comment by notabene00** [comment]
> What branch should I test now?

the same branch, [aqara-wireless-switches](https://github.com/fantomnotabene/HomeyCONZ/tree/aqara-wireless-switches)
"now synced" meant that latest changes in `master` was merged into `aqara-wireless-switches`
`master` has no support for this switches for now
I need confirmation that both versions of the aqara wireless switch are working on this branch
Then I'll merge switches and start working on philips hue remote

> I'm trying the lumi.sensor_86sw2Un wich is the 2016 version. I only have 2 of them. No 2018.

v2018 was tested and working, try yours 2016s :)

**Comment by powermarcel10** [comment]
Yeah I do understand, but the app is not able to find my 2016 devices. Here is a screenshot so you can see im using the right branch.

![IMG_20191211_232750](https://user-images.githubusercontent.com/2340835/70665957-fc696500-1c6d-11ea-9229-1fc3b997ebf0.jpg)

**Comment by notabene00** [comment]
<img width="1136" alt="Снимок экрана 2019-12-12 в 11 19 36" src="https://user-images.githubusercontent.com/9576189/70694695-4afc1b00-1cd1-11ea-98a0-2e2076902268.png">
Check your switch's modelid

**Comment by powermarcel10** [comment]
lumi.sensor_86sw2Un

**Comment by notabene00** [comment]
no idea what's going wrong

**Comment by powermarcel10** [comment]
Hmm thats strange than,. Maybe the 2016 version has other button events?

**Comment by powermarcel10** [comment]
This is how it looks like in the foscon app:

Sory I found it! In the deconz software running on my pi, I have discovered another ID. Its lumi.sensor_86sw2. And the other one is not showing anything..

**Comment by powermarcel10** [comment]
So I found on a website that there are actually 3 of them:

![Naamloos](https://user-images.githubusercontent.com/2340835/70757398-b54ba480-1d3f-11ea-9d1f-292a8b470511.jpg)

Crazy people @ Aqara!!

**Comment by notabene00** [comment]
> Maybe the 2016 version has other button events

events has nothing to do with discovery

> there are actually 3 of them

just added `lumi.sensor_86sw2`, try

**Comment by powermarcel10** [comment]
And they are finally found and working! All buttons are working. Great work and thank for you patience! This one can go to master. 

Sidenote: Maybe its good to make a list of supported devices at the frontpage as the list is to long now for only a screenshot 👍

**Comment by notabene00** [comment]
About list: maybe :)
And great. I’ll merge switches and hue remote into master this evening. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by powermarcel10** [comment]
Great! Than all my devices are working now.. So I dont have to bother you anymore.. Maybe in the future.. Stay tuned! 😋

**Comment by notabene00** [comment]
Hey, what about #10?
Vibration sensor on its way to me :)

Anyway, it was nice to deal with you

Ah. Switches also merged, closing now
